global:
  email-reply-to: dpxtools@salesforce.com
  preprocessor-tag: jenkins-sfci-sfci-managed-preprocessor-PR-6322-latest-itest
stages:
  build:
    - npm-setup:
        yarn-modern: true
    - step:
        name: yarn-build
        image: docker.repo.local.sfdc.net/sfci/docker-images/sfdc_rhel9_nodejs20/sfdc_rhel9_nodejs20_build:latest
        commands:
          - yarn install
          - yarn build
